# Generated by Django 4.2.3 on 2023-07-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('course_type', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'Free Plan'), ('premium', 'Premium Plan')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_file', to='course.course')),
            ],
        ),
    ]
