# Generated by Django 4.2.3 on 2023-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_userprofile_attendance_userprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
